use std::collections::HashMap;

/// Emotion long-form → short code mapping.
#[allow(dead_code)]
pub fn emotion_codes() -> HashMap<&'static str, &'static str> {
    HashMap::from([
        ("vulnerability", "vul"),
        ("vulnerable", "vul"),
        ("joy", "joy"),
        ("joyful", "joy"),
        ("fear", "fear"),
        ("mild_fear", "fear"),
        ("trust", "trust"),
        ("trust_building", "trust"),
        ("grief", "grief"),
        ("raw_grief", "grief"),
        ("wonder", "wonder"),
        ("philosophical_wonder", "wonder"),
        ("rage", "rage"),
        ("anger", "rage"),
        ("love", "love"),
        ("devotion", "love"),
        ("hope", "hope"),
        ("despair", "despair"),
        ("hopelessness", "despair"),
        ("peace", "peace"),
        ("relief", "relief"),
        ("humor", "humor"),
        ("dark_humor", "humor"),
        ("tenderness", "tender"),
        ("raw_honesty", "raw"),
        ("brutal_honesty", "raw"),
        ("self_doubt", "doubt"),
        ("anxiety", "anx"),
        ("exhaustion", "exhaust"),
        ("conviction", "convict"),
        ("quiet_passion", "passion"),
        ("warmth", "warmth"),
        ("curiosity", "curious"),
        ("gratitude", "grat"),
        ("frustration", "frust"),
        ("confusion", "confuse"),
        ("satisfaction", "satis"),
        ("excitement", "excite"),
        ("determination", "determ"),
        ("surprise", "surprise"),
    ])
}

/// Keyword → emotion code signals for plain-text detection.
pub fn emotion_signals() -> &'static [(&'static str, &'static str)] {
    &[
        ("decided", "determ"),
        ("prefer", "convict"),
        ("worried", "anx"),
        ("excited", "excite"),
        ("frustrated", "frust"),
        ("confused", "confuse"),
        ("love", "love"),
        ("hate", "rage"),
        ("hope", "hope"),
        ("fear", "fear"),
        ("trust", "trust"),
        ("happy", "joy"),
        ("sad", "grief"),
        ("surprised", "surprise"),
        ("grateful", "grat"),
        ("curious", "curious"),
        ("wonder", "wonder"),
        ("anxious", "anx"),
        ("relieved", "relief"),
        ("satisf", "satis"),
        ("disappoint", "grief"),
        ("concern", "anx"),
    ]
}

/// Keyword → flag signals for plain-text detection.
pub fn flag_signals() -> &'static [(&'static str, &'static str)] {
    &[
        ("decided", "DECISION"),
        ("chose", "DECISION"),
        ("switched", "DECISION"),
        ("migrated", "DECISION"),
        ("replaced", "DECISION"),
        ("instead of", "DECISION"),
        ("because", "DECISION"),
        ("founded", "ORIGIN"),
        ("created", "ORIGIN"),
        ("started", "ORIGIN"),
        ("born", "ORIGIN"),
        ("launched", "ORIGIN"),
        ("first time", "ORIGIN"),
        ("core", "CORE"),
        ("fundamental", "CORE"),
        ("essential", "CORE"),
        ("principle", "CORE"),
        ("belief", "CORE"),
        ("always", "CORE"),
        ("never forget", "CORE"),
        ("turning point", "PIVOT"),
        ("changed everything", "PIVOT"),
        ("realized", "PIVOT"),
        ("breakthrough", "PIVOT"),
        ("epiphany", "PIVOT"),
        ("api", "TECHNICAL"),
        ("database", "TECHNICAL"),
        ("architecture", "TECHNICAL"),
        ("deploy", "TECHNICAL"),
        ("infrastructure", "TECHNICAL"),
        ("algorithm", "TECHNICAL"),
        ("framework", "TECHNICAL"),
        ("server", "TECHNICAL"),
        ("config", "TECHNICAL"),
    ]
}
