name: Audit

on:
  workflow_call:
  schedule:
    - cron: "0 0 * * *" # daily at midnight

permissions: {}

jobs:
  run:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      issues: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions-rust-lang/audit@72c09e02f132669d52284a3323acdb503cfc1a24 # v1.2.7
