name: Cargo

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions: {}

jobs:
  audit:
    name: Audit
    uses: ./.github/workflows/audit.yml
    permissions:
      contents: read
      issues: write

  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml
    permissions:
      contents: read

  test:
    name: Test
    needs: [lint]
    uses: ./.github/workflows/test.yml
    permissions:
      contents: read
